from django.contrib import admin

# Register your models here.
""" models are created as classes in the models.py file. Thus we have a model Post which describes the schema for a post. 
This is used by the makemigrate and migrate commands to geerate the database table 

When you register a model in the Django administration site then you get a user friendly interface generated by 
introspecting your models which allows you to list, edit create and delete objects in an easy way"""

from .models import Post

#admin.site.register(Post) 
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    # define fields to display on admin page
    list_display = ('title', 'slug', 'author', 'publish', 'status')
    # define which fields the display can be filtered by (right hand side bar)
    list_filter = ('status', 'created', 'publish', 'author')
    # defines what fields are included in any search (box at top)
    search_fields = ('title', 'body')
    # slug field automatically filled with content of title field
    prepopulated_fields = {'slug': ('title',)}
    
    #raw_id_fields = ('author',)
    date_hierarchy = 'publish'
    ordering = ('status', 'publish')